groups:
  - name: car-rental-alerts
    rules:
      # Alertas de Sistema
      - alert: HighCPUUsage
        expr: system_cpu_usage > 0.8
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Alto uso de CPU"
          description: "CPU está com {{ $value | humanizePercentage }} de uso há mais de 5 minutos"

      - alert: HighMemoryUsage
        expr: system_cpu_usage > 0.9
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Alto uso de memória"
          description: "Memória está com {{ $value | humanizePercentage }} de uso há mais de 5 minutos"

      # Alertas de Aplicação
      - alert: HighErrorRate
        expr: rate(http_server_requests_seconds_count{status=~"5.."}[5m]) > 0.1
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Alta taxa de erros HTTP"
          description: "Taxa de erros HTTP 5xx está acima de 10% nos últimos 5 minutos"

      - alert: HighLatency
        expr: histogram_quantile(0.95, rate(http_server_requests_seconds_bucket[5m])) > 1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Alta latência"
          description: "95º percentil da latência está acima de 1 segundo"

      # Alertas de Negócio
      - alert: LowVehicleAvailability
        expr: vehicle_availability{available="true"} < 2
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "Baixa disponibilidade de veículos"
          description: "Menos de 2 veículos disponíveis há mais de 10 minutos"

      - alert: HighRentalRate
        expr: rate(rental_created_total[1h]) > 10
        for: 5m
        labels:
          severity: info
        annotations:
          summary: "Alta taxa de locações"
          description: "Mais de 10 locações por hora nos últimos 5 minutos"

      - alert: FailedAuthenticationAttempts
        expr: rate(authentication_failures_total[5m]) > 5
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Múltiplas tentativas de autenticação falhas"
          description: "Mais de 5 tentativas de autenticação falhas nos últimos 5 minutos" 