version: '3.8'

services:
  # Aplicação Spring Boot
  app:
    build: ./backend
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - JWT_SECRET=${JWT_SECRET}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
    networks:
      - monitoring

  # Frontend React
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:${APP_PORT}/api
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - app
    networks:
      - monitoring

  # Prometheus
  prometheus:
    image: prom/prometheus:v2.45.0
    ports:
      - "${PROMETHEUS_PORT}:${PROMETHEUS_PORT}"
    volumes:
      - ./backend/src/main/resources/prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    networks:
      - monitoring

  # Alertmanager
  alertmanager:
    image: prom/alertmanager:v0.25.0
    ports:
      - "${ALERTMANAGER_PORT}:${ALERTMANAGER_PORT}"
    volumes:
      - ./backend/src/main/resources/alertmanager:/etc/alertmanager
      - alertmanager_data:/alertmanager
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
    environment:
      - ALERTMANAGER_EMAIL_FROM=${ALERTMANAGER_EMAIL_FROM}
      - ALERTMANAGER_EMAIL_TO=${ALERTMANAGER_EMAIL_TO}
      - ALERTMANAGER_EMAIL_SMARTHOST=${ALERTMANAGER_EMAIL_SMARTHOST}
      - ALERTMANAGER_EMAIL_USERNAME=${ALERTMANAGER_EMAIL_USERNAME}
      - ALERTMANAGER_EMAIL_PASSWORD=${ALERTMANAGER_EMAIL_PASSWORD}
      - SLACK_WEBHOOK_URL=${SLACK_WEBHOOK_URL}
      - SLACK_CHANNEL=${SLACK_CHANNEL}
    networks:
      - monitoring

  # Grafana
  grafana:
    image: grafana/grafana:10.0.0
    ports:
      - "${GRAFANA_PORT}:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GF_SECURITY_SECRET_KEY=${GRAFANA_SECRET_KEY}
    volumes:
      - ./backend/src/main/resources/grafana/dashboards:/var/lib/grafana/dashboards
      - ./backend/src/main/resources/grafana/grafana.ini:/etc/grafana/grafana.ini
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - monitoring

  # Node Exporter (para métricas do sistema)
  node-exporter:
    image: prom/node-exporter:v1.6.0
    ports:
      - "${NODE_EXPORTER_PORT}:${NODE_EXPORTER_PORT}"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    networks:
      - monitoring

volumes:
  prometheus_data:
  alertmanager_data:
  grafana_data:

networks:
  monitoring:
    driver: bridge 