{
 "title": "Métricas de Negócio",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Veículos Disponíveis",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "vehicle_availability{available=\"true\"}",
     "legendFormat": "Veículos Disponíveis"
    }
   ]
  },
  {
   "title": "Taxa de Locações",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "rate(rental_created_total[5m])", "legendFormat": "Locações/min" }
   ]
  },
  {
   "title": "Tentativas de Autenticação Falhas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(authentication_failures_total[5m])",
     "legendFormat": "Falhas/min"
    }
   ]
  },
  {
   "title": "Taxa de Finalização de Locações",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(rental_completed_total[5m])",
     "legendFormat": "Finalizações/min"
    }
   ]
  }
 ]
}