spring:
  application:
    name: carrent-api
  datasource:
    url: jdbc:mysql://servermysqlcn1.mysql.database.azure.com:3306/victor?useSSL=true&requireSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: userdb
    password: admin@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    open-in-view: false
  sql:
    init:
      mode: never
  h2:
    console:
      enabled: false
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    validate-on-migrate: false
  security:
    jwt:
      secret: ${JWT_SECRET:${application.security.jwt.secret-key}}
      expiration: ${JWT_EXPIRATION:${application.security.jwt.expiration}}

server:
  port: 8080
  servlet:
    context-path: /api

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /management
    endpoint:
      health:
        show-details: always
      metrics:
        enabled: true
      prometheus:
        enabled: true
  metrics:
    tags:
      application: carrent-api
    distribution:
      percentiles-histogram:
        http.server.requests: true
      sla:
        http.server.requests: 10ms, 50ms, 100ms, 200ms, 500ms
    sampling:
      probability: 1.0

logging:
  level:
    root: INFO
    com.carrent: INFO
    org.springframework.web: WARN
    org.hibernate: WARN
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: INFO
    io.micrometer: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/carrent-api-dev.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30

springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: method
    tags-sorter: alpha
    try-it-out-enabled: true
    filter: true
  show-actuator: true
  packages-to-scan: com.carrent.web.controller
  paths-to-match: /**
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  group-configs:
    - group: 'default'
      paths-to-match: /**
      packages-to-scan: com.carrent.web.controller 