spring:
  datasource:
    url: jdbc:h2:mem:carrentdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
  flyway:
    enabled: false

server:
  port: 8081
  servlet:
    context-path: /api

logging:
  level:
    root: WARN
    com.carrent: DEBUG
    org.springframework.web: WARN
    org.hibernate: WARN

springdoc:
  api-docs:
    path: /api-docs
    enabled: false
  swagger-ui:
    path: /swagger-ui.html
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never
    metrics:
      enabled: false
    prometheus:
      enabled: false

security:
  jwt:
    secret: test-secret-key
    expiration: 86400000 