spring:
  application:
    name: carrent-api
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}?useSSL=true&requireSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: ${JPA_SHOW_SQL:false}
    open-in-view: false
  sql:
    init:
      mode: never
  h2:
    console:
      enabled: false
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    clean-disabled: false
    validate-on-migrate: true
    out-of-order: true
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
  security:
    jwt:
      secret: ${JWT_SECRET}
      expiration: ${JWT_EXPIRATION}

server:
  port: ${APP_PORT:8080}
  servlet:
    context-path: /api

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /management
    endpoint:
      health:
        show-details: always
      metrics:
        enabled: true
      prometheus:
        enabled: true
  metrics:
    tags:
      application: carrent-api
    distribution:
      percentiles-histogram:
        http.server.requests: true
      sla:
        http.server.requests: 10ms, 50ms, 100ms, 200ms, 500ms
    sampling:
      probability: 1.0

logging:
  level:
    root: ${LOG_LEVEL_ROOT:WARN}
    com.carrent: ${LOG_LEVEL_APP:INFO}
    org.springframework.web: ${LOG_LEVEL_SPRING_WEB:ERROR}
    org.hibernate: ${LOG_LEVEL_HIBERNATE:ERROR}
    org.hibernate.SQL: ${LOG_LEVEL_HIBERNATE_SQL:ERROR}
    org.hibernate.type.descriptor.sql.BasicBinder: ${LOG_LEVEL_HIBERNATE_BINDER:ERROR}
    io.micrometer: ${LOG_LEVEL_MICROMETER:ERROR}
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: ${LOG_FILE_PATH:logs/carrent-api-dev.log}
  logback:
    rollingpolicy:
      max-file-size: ${LOG_MAX_FILE_SIZE:10MB}
      max-history: ${LOG_MAX_HISTORY:30}

springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: method
    tags-sorter: alpha
    try-it-out-enabled: true
    filter: true
  show-actuator: true
  packages-to-scan: com.carrent.web.controller
  paths-to-match: /**
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  group-configs:
    - group: 'default'
      paths-to-match: /**
      packages-to-scan: com.carrent.web.controller 